In [ ]:
#import libraries

import numpy as np 
import pandas as pd 
import system
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import KFold   
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [ ]:
#loading dataset
train_path = '/content/drive/MyDrive/mlba_2_data/kaggle_train.csv'
test_path = '/content/drive/MyDrive/mlba_2_data/kaggle_test.csv'
train_data = pd.read_csv(train_path)
test_data  = pd.read_csv(test_path)

scaler = StandardScaler()
X1  = test_data.iloc[:,:]
y = train_data.iloc[:,1] 
ID = [] 
X1

,ID,ACAN,AGER,ALPK1,ANKRD17,APOB,APPL1,APPL2,ARRB2,ASGR1,...,UBE2N,UBE2V1,UBQLN1,UFD1,UNC93B1,USP17L2,VCAN,WDFY1,XIAP,ZCCHC3
0,1001,91.3265,132.5226,331.5548,1658.7666,0.0000,1068.6189,571.2868,699.8387,9.4305,...,1525.2513,3320.8537,2817.7193,1397.1957,367.7876,0.4963,699.3424,995.6570,1219.0098,840.7991
1,1002,17.5971,183.2524,558.8592,2321.6019,0.6068,929.0049,783.9806,1039.4417,27.3058,...,2489.6845,2102.5485,3799.1505,906.5534,1187.5000,0.0000,1967.2330,1529.7330,1083.1311,510.3155
2,1003,120.9309,221.8022,331.8437,891.7940,0.0000,309.4915,403.4852,1430.5385,49.8625,...,1760.6628,4822.9092,3718.4831,1907.9521,1732.0061,0.0000,1190.9692,1156.5812,710.6842,689.4783
3,1004,12.0930,41.8605,886.5116,2216.7442,0.0000,792.5581,1012.0930,637.2093,3.7209,...,1872.5581,2342.0093,3280.9302,1115.3116,773.0233,0.0000,63.2558,1065.1163,1385.1163,563.7209
4,1005,84.0622,34.4995,145.7726,1266.2779,0.4859,1362.4879,830.9038,1064.1399,85.5199,...,1932.9446,3220.9184,3153.5471,1168.6054,965.5005,0.0000,1168.6103,581.6327,878.5228,607.8717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1058,208.9873,60.8119,825.6712,1565.6918,0.0000,1044.0800,1235.0807,1266.7714,46.2513,...,2769.0819,4627.6985,2351.1072,759.7203,951.5775,0.0000,461.6564,1303.6012,1592.2435,912.1782
58,1059,2.0776,150.2770,815.7895,1827.5623,0.6925,1547.7839,760.3878,751.3850,2.0776,...,2425.2078,2342.1053,1223.6842,1278.3657,775.6233,0.0000,114.9584,1076.1773,1485.4571,567.8670
59,1060,68.6071,93.9709,390.8524,2483.9917,0.4158,573.8046,784.6154,870.2703,10.3950,...,2094.3867,2447.3763,2848.2328,1508.0998,1472.7651,0.0000,4277.7547,1402.0790,1367.9834,543.8669
60,1061,24.2669,110.7179,339.7371,2011.1223,1.0111,818.5035,1622.8514,1023.7614,42.9727,...,1440.8493,2525.3589,2431.7492,1882.6795,646.6127,2.0222,1320.0202,1005.0556,1280.5865,1353.8928
61,1062,24.7838,64.5411,414.0958,2906.9317,0.0000,973.7963,915.4511,578.2884,7.2286,...,2518.1361,5760.4079,4942.3002,1043.4955,844.1978,0.0000,186.3947,589.6476,1308.8938,881.8898

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
y.head
scaler = StandardScaler()
X  = pd.DataFrame(scaler.fit_transform(X1))
X

,0,1,2,3,4,5,6,7,8,9,...,309,310,311,312,313,314,315,316,317,318
0,-1.704336,0.753966,0.788139,-0.703424,-0.466797,-0.346403,-0.089156,-0.728260,-0.516094,-0.335531,...,-0.713803,0.476823,-0.250093,-0.079493,-1.004302,1.002577,-0.205486,-0.310417,-0.485746,0.632556
1,-1.648456,-0.550575,1.988830,0.153127,0.656528,-0.305360,-0.406073,-0.391481,0.434938,0.630954,...,0.997095,-0.787482,0.842451,-0.625791,-0.124012,-0.398946,0.439386,0.556486,-0.822384,-0.696354
2,-1.592576,1.277776,2.901241,-0.702335,-1.766608,-0.346403,-1.812336,-0.993956,1.530175,1.850554,...,-0.296185,2.035591,0.752651,0.489200,0.460734,-0.398946,0.044564,-0.049208,-1.745114,0.024079
3,-1.536697,-0.647963,-1.357685,1.387818,0.478823,-0.346403,-0.715800,-0.030288,-0.691483,-0.644239,...,-0.097683,-0.538980,0.265561,-0.393352,-0.569119,-0.398946,-0.529012,-0.197672,-0.074220,-0.481605
4,-1.480817,0.625434,-1.531908,-1.403506,-1.131959,-0.313538,0.577911,-0.317183,0.504104,3.778485,...,0.009442,0.373114,0.123756,-0.334013,-0.362418,-0.398946,0.033192,-0.982454,-1.329297,-0.304070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1.480817,2.835814,-0.909137,1.158553,-0.624534,-0.346403,-0.144858,0.322790,1.071558,1.655303,...,1.492745,1.833010,-0.769532,-0.789280,-0.377370,-0.398946,-0.326378,0.189432,0.438934,0.919579
58,1.536697,-0.825172,1.208356,1.121316,-0.180735,-0.299564,0.998524,-0.428838,-0.371743,-0.733089,...,0.882714,-0.538880,-2.024596,-0.211803,-0.566327,-0.398946,-0.502715,-0.179718,0.174372,-0.464933
59,1.592576,0.351977,-0.124317,-0.479973,0.931735,-0.318279,-1.212359,-0.390476,-0.038813,-0.283382,...,0.295840,-0.429634,-0.216125,0.043991,0.182334,-0.398946,1.614560,0.349280,-0.116667,-0.561440
60,1.648456,-0.432562,0.272057,-0.672590,0.130350,-0.278015,-0.656905,0.936785,0.391027,1.478035,...,-0.863532,-0.348707,-0.679760,0.461061,-0.704872,5.311630,0.110202,-0.295162,-0.333191,2.695760
61,1.704336,-0.423416,-0.820872,-0.392385,1.648503,-0.346403,-0.304399,-0.183311,-0.856487,-0.454584,...,1.047568,3.008487,2.115022,-0.473315,-0.492685,-0.398946,-0.466381,-0.969445,-0.263060,0.797786

Variance threshold

In [ ]:
from sklearn.feature_selection import VarianceThreshold
sel = VarianceThreshold(1.0) # This will remove all zero-variance features
sf = sel.fit_transform(X) # The file will be saved in sf
sc = X.columns[sel.get_support(indices=True)] #This saves the columns names in sc variable
X[sc].head()
RES = X[sc]
RES.to_csv('ANS.csv',index = False)

In [ ]:
RES

,3,4,5,6,7,10,11,12,14,17,...,287,289,290,297,299,309,311,314,316,317
0,-0.703424,-0.466797,-0.346403,-0.089156,-0.728260,-0.217095,0.070201,-0.263389,-1.347824,-0.253409,...,-0.646088,-0.721910,-0.198731,-0.455733,-0.386183,-0.713803,-0.250093,1.002577,-0.310417,-0.485746
1,0.153127,0.656528,-0.305360,-0.406073,-0.391481,1.467336,-0.916347,0.311529,0.183714,-0.253917,...,1.020696,0.102635,-0.314009,1.111160,-0.490945,0.997095,0.842451,-0.398946,0.556486,-0.822384
2,-0.702335,-1.766608,-0.346403,-1.812336,-0.993956,1.255055,-1.100151,-0.270388,-0.290677,-0.254576,...,-0.628477,-1.029782,-0.197319,1.517559,-0.459854,-0.296185,0.752651,-0.398946,-0.049208,-1.745114
3,1.387818,0.478823,-0.346403,-0.715800,-0.030288,-0.521393,-0.382491,-0.270388,1.654640,-0.254804,...,-0.574106,-0.625761,-0.334803,0.344971,-0.444948,-0.097683,0.265561,-0.398946,-0.197672,-0.074220
4,-1.403506,-1.131959,-0.313538,0.577911,-0.317183,-0.776140,1.022610,-0.270388,-1.319531,-0.254861,...,-0.597624,1.065189,-0.168287,-0.455733,-0.502137,0.009442,0.123756,-0.398946,-0.982454,-1.329297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1.158553,-0.624534,-0.346403,-0.144858,0.322790,-0.552373,-0.809238,-0.222071,0.663106,-0.254808,...,5.796465,-0.284938,7.590142,-0.455733,2.225475,1.492745,-0.769532,-0.398946,0.189432,0.438934
58,1.121316,-0.180735,-0.299564,0.998524,-0.428838,-0.039323,-0.722255,-0.270388,1.449305,-0.254603,...,-0.534707,-0.139039,-0.097483,-0.455733,-0.255201,0.882714,-2.024596,-0.398946,-0.179718,0.174372
59,-0.479973,0.931735,-0.318279,-1.212359,-0.390476,-0.096956,-0.100259,-0.264524,0.316875,-0.254861,...,1.339170,-0.009880,-0.149565,-0.455733,-0.443343,0.295840,-0.216125,-0.398946,0.349280,-0.116667
60,-0.672590,0.130350,-0.278015,-0.656905,0.936785,-0.770636,4.123501,-0.056492,-1.902359,-0.232076,...,0.285175,-0.554892,-0.265505,-0.455733,-0.393353,-0.863532,-0.679760,5.311630,-0.295162,-0.333191
61,-0.392385,1.648503,-0.346403,-0.304399,-0.183311,-0.550679,2.869607,-0.270388,0.784882,-0.254861,...,-0.648899,-1.005186,-0.264028,-0.455733,-0.457697,1.047568,2.115022,-0.398946,-0.969445,-0.263060

In [ ]:
!ls

ANS.csv  drive	sample.csv  sample_data

model information gain

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import mutual_info_classif
fs = SelectKBest(score_func=mutual_info_classif, k=50) # This will select top 50 features using mutual information gain
sf = fs.fit_transform(X,y) # It learns relationship and transfrom the data
sc = X.columns[fs.get_support(indices=True)] #This saves the columns names in sc variable
X[sc].head() #This will show the first few rows of selected features

ValueError: ignored

ANOVA

In [ ]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
fs = SelectKBest(score_func=f_classif, k=50) # This will select top 50 features using ANOVA F-value
sf = fs.fit_transform(X,y) # It learns relationship and transfrom the data
sc = X.columns[fs.get_support(indices=True)] #This saves the columns names in sc variable
X[sc].head() #This will show the first few rows of selected features

WRAPPER methods

RFE

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
rfe = RFE(lr) #It assigns weights to features using logistic regression
sf = rfe.fit(X, y)  # It learns relationship and transfrom the data
sc = X.columns[rfe.get_support(indices=True)] #This saves the columns names in sc variable
X[sc].head() #This will show the first few rows of selected features
X[sc].to_csv('result.csv',header=False,index=False)

SFS

In [ ]:
import joblib

sys.modules['sklearn.externals.joblib'] = joblib
from mlxtend.feature_selection import SequentialFeatureSelector
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
sfs = SequentialFeatureSelector(knn)#It assigns weights to features using KNN
sf = sfs.fit_transform(X, y) # It learns relationship and transfrom the data
sc = list(sfs.k_feature_names_) #This saves the feature names in the list variable sc
train_data[sc].head()